var arr = [
    //{"joke": "Hey baby, \n\n So by the time you're getting this I should be on a plane to come see you. So if you're wondering why you're getting a text from me from this weird number, it's because this is a virtual bot I made. I know you always say that love you my stupid Dad jokes, so I made this program as your first christmas gift. I currated a database of dad jokes and this robot will send them to you every morning at 8 am just as your about to start your work day. I love you babe, and hope you enjoy it, Merry Christmas cutie. \n\n  Why do cows have hooves and not feet? \n\n\nBecause they lactose \n"},
    {"joke": "How does a gingerbread man stay warm at night? \n\nCookie Sheets \n"},
    {"joke": "What's the biggest rip-off in fashion? \n\n\nVelcro"},
    {"joke": "What days are strongest? \n\n\nSaturday and Sunday because the rest are week days \n"},
    {"joke": "Why did the blind man fall into a watering hole? \n\n\nBecause he couldn't see that well\n"},
    {"joke": "What did the flag say to his friend? \n\n\nNothing, he waved.\n"},
    {"joke": "How does Moses make his tea? \n\n\n Hebrews it\n"},
    {"joke": "Did you here about the kid napping in broad daylight outside the school? \n\n\nIt's okay though, he woke up\n"},
    {"joke": "My son's math teachers says he's average, I think he's mean\n"},
    {"joke": "Why don't ducks make good detectives? \n\n\nBecause they can't quack the case\n"},
    {"joke": "What do you call an academic paper written by a Dad? \n\n\nA Parent thesis\n"},
    {"joke": "What do you get when you cross a vampire and a snowman? \n\n\nFrost Bite\n"},
    {"joke": "How do you pick a prestigious cow? \n\n\nBecause they're outstanding in their field\n"},
    {"joke": "A duck goes to the checkout counter and notices he doesn't have enough money for his purchase. \n\n\nHe asks the cashier, \'Can I put it on my bill?\'\n"},
    {"joke": "Why does the Earth like to twirl? \n\n\nBecause it makes its day\n"},
    {"joke": "What is a mathmaticians favorite bra? \n\n Algerbra\n"},
    {"joke": "When does a joke become a Dad joke \n\n\nWhen it's fully groan\n"},
    {"joke": "What do you call a salt shaker with a gun? \n\n\n Assault with a deadly weapon\n"},
    {"joke": "Why did the can crush quit his job> \n\n\nBecause it was soda pressing\n"},
    {"joke": "Why did the skeleton go to talk with customer service? \n\n\nBecause he had a bone to pick\n"},
    {"joke": "What is the best angle from which to approach any problem? \n\n\nThe TRYangle\n"},
    {"joke": "Why did the cofee call 911? \n\n\nBecause it was muggged\n"},
    {"joke": "Why does a chicken coop only have 2 door? \n\n\nBecause if it had 4 doors, it would be a chicken Sedan\n"},
    {"joke": "Why can't you hear a ptderodactyl going to the bathroom? \n\n\nBecause the \'p\' is silent\n"},
    {"joke": "What do Lawyers wear to court? \n\n\nA law suit\n"},
    {"joke": "What do you call a person who takes care of chickens? \n\n\nA chicken tender\n"},
    {"joke": "Why is it so hard to make puns for kleptomaniacs? \n\n\nTHey are always taking things literally\n"},
    {"joke": "It cost the government more to make pennies than what they're worth. That barely makes cents.\n"},
    {"joke": "How does NASA prepare for a party? \n\n\nThey Planet\n"},
    {"joke": "Why does the scientist hate paper? \n\n\nBecause it's tearable"},
    {'joke': "Why did the bouncer not let the note into the club?\n\n\nBecause he was A minor"},
    {'joke': "Why did the two satellites have the best wedding?\n\n\nBecause their reception was amazing"},
    {'joke': "I asked my doctor about a sausage-shaped blind spot in my eye\n\n\nHe said \'Wurst you'll ever see.\'"},
    {'joke': "How do you cut the ocean in half?\n\n\nYou use a sea-saw"},
    {'joke': "Why does the donkey wear a leather jacket\n\n\nBecause it's a bad ass"},
    {'joke': "What is an alligator's favorite shoe?\n\n\nCrocs"},
    {'joke': "Why do peanuts hate almonds?\n\n\nBecause they're nuts"},
    {'joke': "Why did the clones make such bad roommates\n\n\nBecause they couldn't live with themselves"},
    {'joke': "What kind of award did the inventor of the knock-knock joke get?\n\n\nShe got the no bell prize"},
    {'joke': "Why do programmers wear glasses?\n\n\nBecause they can't C"},
    {'joke': "How do monkeys go down stairs?\n\n\nThey slide down the bananaster"},
    {'joke': "Why did the lawyer shut off all the electricity?\n\n\nBecause it was a power move."},
    {'joke': "Why can't Americans switch over to Kilograms?\n\n\nBecause it would cause MASS confusion"},
    {'joke': "How do you know when a pool is safe for diving\n\n\nIt deep ends"},
    {'joke': "What is the hardest part about sky diving?\n\n\nThe ground"},
    {'joke': "What do prisoners use to call each other?\n\n\nCell phones"},
    {'joke': "I gave all my dead batteries away today, free of charge\n"},
    {'joke': "Did you hear about the scientist who was lab partners with a pot of boiling water?\n\n\nShe had a very a steamed colleague"},
    {'joke': "Why did the tomato blush?\n\n\nBecause it saw the salad dressing"},
    {'joke': "Why is the plumber tired of his job?\n\n\nBecause it's the same old shit"},
    {'joke': "How do you make a kleenex dance?\n\n\nYou put a lil boogie in it"},
    {'joke': "A Father in Iraq gifted his daughter a new purse for her birthday\n\n\nShe replied \'Thanks for the Baghdad\'"},
    {'joke': "Why are fish easy to weigh?\n\n\nBecause they have their own scales"},
    {'joke': "What do you call a group of whales playing instruments?\n\n\nAn Orca-stra"},
    {'joke': "Why did the number 4 ruin the party?\n\n\nBecause he is 2 square"},
    {'joke': "I bought shoes from a drug dealer once. I don't know what he laced them with, but I was tripping all day"},
    {'joke': "Why did the student stop following their dreams?\n\n\nBecause all they ever posted was trashy memes"},
    {'joke': "How do you find Will Smith in the Snow?\n\n\nFresh Prints"},
    {"joke": "What does the dentist of the year get?\n\n\nA little plaque"},
    {"joke": "What did the baby corn say to mama corn?\n\n\n\'Where's popcorn?\'"},
    {"joke": "What do you call a Nun who is sleep walking?\n\n\nA Roamin\' Catholic"},
    {"joke": "Why can't T-Rex's clap their hands?\n\n\nBecause they're extinct"},
    {"joke": "How did the hamburger introduce his girlfriend?\n\n\n\'Meat Patty\'"},
    {"joke": "Why was the scuba diver such a great philopsher?\n\n\nBecause he was so deep"},
    {"joke": "What’s the difference between a poorly dressed man on a tricycle and a well dressed man on a bicycle?\n\n\nAttire"},
    {"joke": "What do you call the mixture of a donkey and a deer?\n\n\nDat Ass Doe"},
    {"joke": "If you are Russian when you go to the bathroom and you're Finnish when you leave the bathroom. What are you when you're in the bathroom?\n\n\nEuropean"},
    {"joke": "Why is it a bad idea to keep your goldfish in a tank?\n\n\nBecause they don't know how to drive"},
    {"joke": "What do you call a cow that just gave birth?\n\n\nDecalfinated"},
    {"joke": "How can you tell if a joke is a dad joke?\n\n\nIf the punchline is apparent"},
    {"joke": "Why is it better to get hit in the head with a bottle of coca-cola than a bottle of water?\n\n\nBecause it's a soft drink"},
    {'joke': "If athletes get athletes foot, what do astronauts get?\n\n\nMissle toe"}

];

module.exports.arr = arr;
